items:
  # Clock
  ARCHEAN_mod.Clock:
    max_stack: 256

  # Valve
  ARCHEAN_mod.ValveHandle:
    max_stack: 256

  # Infinite
  ARCHEAN_mod.InfiniteLV:
    max_stack: 256
  ARCHEAN_mod.InfiniteHV:
    max_stack: 256
  ARCHEAN_mod.InfiniteItems:
    max_stack: 256
  ARCHEAN_mod.InfiniteFluid:
    max_stack: 256
  ARCHEAN_mod.InfiniteData:
    max_stack: 256

recipes:
  # Clock
  - label: Clock
    context: crafter
    category: components
    time: 2
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 1
    output:
      ARCHEAN_mod.Clock: 1

  # Valve
  - label: Valve Handle
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_celestial.Iron: 10
      ARCHEAN_parts.Connector: 1
    output:
    ARCHEAN_mod.ValveHandle: 1

  # Infinite
  - label: InfiniteData
    context: crafter
    category: components
    time: 1
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 2
      ARCHEAN_parts.Circuit: 1
    output:
      ARCHEAN_mod.InfiniteData
